<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\User;

class DeleteRecordFromRedis extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'redis:delete {user_id}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Delete all records from a specific user. To be used to remove logs generated by spam.';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        if (! $user = User::find($this->argument('user_id')))
            return $this->info('A user with id of ' . $this->argument('user_id') . ' does not exist.');

        if (testing() || $this->confirm('This will delete all records from ' . $user->full_name . '. Are you sure?')) {
            \Redis::del($user->redisKey('app'));
            \Redis::del($user->redisKey('web'));
            \Redis::del($user->redisKey('webapp'));

            return $this->info($user->first_name . '\'s logs have been removed.');
        }
    }
}
