const assert = require('assert');
const {textColor, fitText} = require('../../resources/js/views/escore');
assert.strictEqual(textColor('#00a2ff'), '#000000');
assert.strictEqual(textColor('#000000'), '#ffffff');
assert.strictEqual(textColor('#ffffff'), '#000000');
const measure = (text, size) => Array.from(text).length * size * 0.6;
const title = fitText('A very long collection title '.repeat(5), 60, 460, 190, measure);
assert(title.size < 60);
assert(title.text.split('\n').length * title.size * 1.2 <= 190);
assert.strictEqual(title.text.replace(/\s+/g, ''), 'A very long collection title '.repeat(5).replace(/\s+/g, ''));
const description = fitText('For Late Elementary\nto Beginner levels', 26, 460, 235, measure);
assert.strictEqual(description.text, 'For Late Elementary\nto Beginner levels');
const oversizedWord = 'é'.repeat(160);
const wrappedWord = fitText(oversizedWord, 60, 460, 190, measure);
assert.strictEqual(wrappedWord.text.replace(/\n/g, ''), oversizedWord);
assert(wrappedWord.text.split('\n').every(line => measure(line, wrappedWord.size) <= 460));
const manyBreaks = fitText('A description line.\n'.repeat(30), 26, 460, 235, measure);
assert(manyBreaks.size > 8);
assert(manyBreaks.text.split('\n').length * manyBreaks.size * 1.2 <= 235);
console.log('Passed: eScore cover contrast, fitted cover text, explicit line breaks and Unicode wrapping.');
